//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class ___VARIABLE_ModuleName___Interactor {
    
    var presenter: ___VARIABLE_ModuleName___PresenterProtocol?
    
}

extension ___VARIABLE_ModuleName___Interactor: ___VARIABLE_ModuleName___InteractorProtocol {
    
}
