//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import Foundation

//MARK: Router -
protocol ___VARIABLE_ModuleName___RouterProtocol {

}
//MARK: Presenter -
protocol ___VARIABLE_ModuleName___PresenterProtocol {

}

//MARK: Interactor -
protocol ___VARIABLE_ModuleName___InteractorProtocol {

}

//MARK: View -
protocol ___VARIABLE_ModuleName___ViewProtocol {

}
