//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class ___VARIABLE_ModuleName___Presenter {
    
    private var view: ___VARIABLE_ModuleName___ViewProtocol?
    var interactor: ___VARIABLE_ModuleName___InteractorProtocol?
    private let router: ___VARIABLE_ModuleName___RouterProtocol
    
    init(interface: ___VARIABLE_ModuleName___ViewProtocol, interactor: ___VARIABLE_ModuleName___InteractorProtocol?, router: ___VARIABLE_ModuleName___RouterProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    
    /*                        -,-----------------------------
     _.._         Oi, ___FULLUSERNAME___! eu sou a Presenter!
     ,'      `.      Estava te esperando seu SUCULENTO!!!
     /  __) __` \     -,-----------------------------
     (  (`-`(-')  ) _.-'
     /)  \  = /  (
     /'    |--' .  \
     (  ,---|  `-.)__`
     )(  `-.,--'   _`-.
     '/,'          (  Uu",
     (_       ,    `/,-' )
     `.__,  : `-'/  /`--'
     |     `--'  |
     `   `-._   /
     \        (
     /\ .      \.
     / |` \     ,-\
     /  \| .)   /   \
     ( ,'|\    ,'     :
     | \,`.`--"/      }
     `,'    \  |,'    /
     / "-._   `-/      |
     "-.   "-.,'|     ;
     /        _/["---'""]
     :        /  |"-     '
     '           |      /
     */

    
}

extension ___VARIABLE_ModuleName___Presenter: ___VARIABLE_ModuleName___PresenterProtocol {

}
