//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class ___VARIABLE_ModuleName___Router: BaseRouter {
    
    static func makeController() -> ___VARIABLE_ModuleName___ViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ___VARIABLE_ModuleName___ViewController()
        let interactor = ___VARIABLE_ModuleName___Interactor()
        let router = ___VARIABLE_ModuleName___Router(viewController: view)
        let presenter = ___VARIABLE_ModuleName___Presenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
}

extension ___VARIABLE_ModuleName___Router: ___VARIABLE_ModuleName___RouterProtocol {

}
